version: '3'

services:
  teachteam-mysql-db:
    image: mysql:8.0
    container_name: devo-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devo
      MYSQL_PASSWORD: supersecreto
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: devodb